version: 2

project_name: syl-md2doc

builds:
  - id: syl-md2doc
    main: .
    binary: syl-md2doc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X syl-md2doc/cmd.Version={{ .Version }}
        -X syl-md2doc/cmd.Commit={{ .Commit }}
        -X syl-md2doc/cmd.BuildTime={{ .Date }}

archives:
  - id: default
    builds:
      - syl-md2doc
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: hooziwang
    name: syl-md2doc
  prerelease: auto

brews:
  - name: syl-md2doc
    repository:
      owner: hooziwang
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/hooziwang/syl-md2doc"
    description: "把 Markdown 文件批量转换为 Word(docx) 的命令行工具"
    dependencies:
      - name: pandoc
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
    test: |
      system "#{bin}/syl-md2doc", "--version"

scoops:
  - name: syl-md2doc
    repository:
      owner: hooziwang
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/hooziwang/syl-md2doc"
    description: "把 Markdown 文件批量转换为 Word(docx) 的命令行工具"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
